packages:
  - .

# 重複排除
dedupePeers: true

catalog:
  rolldown: 1.2.9
  rolldown-plugin-dts: 0.28.6
  typescript: 7.0.2
  vitest: 5.0.1
  '@biomejs/biome': 2.5.14
  '@types/aws-lambda': 8.10.163
  '@types/node': 26.6.1
  '@vitest/coverage-v8': 5.0.1

overrides:
  # CVE-2026-67213
  nanoid: ^3.3.17
  rolldown: 'catalog:'

# リリースから一定時間経過していないか、信頼性低下したパッケージはインストールしない
minimumReleaseAge: 2880 # 2d
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade

# 特殊なソースからの依存関係をインストールしない
blockExoticSubdeps: true
